version: '2'

services:
  website:
    build: .
    links:
      - db_user
    ports:
      - '8080:80'

  db_user:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: CLOUD
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/Cloud.sql"
