version: '2'

services:
  website:
    build: .
    links:
      - db_user
    volumes:
      - './count:/COUNT:rw'
    ports:
      - '80:80'

  db_user:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user" 
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: "CLOUD"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/Cloud.sql"
