version: '2'

services:
  website:
    build: .
    links:
      - db_ride
    ports:
      - '80:80'
    environment:
      DBAAS_IP: "52.206.4.84"

  db_ride:
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: CLOUD
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/Cloud.sql"
