version: '3'

services:
  website:
    image: master
    build: .
    hostname: master
    environment:
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: CLOUD
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/Cloud.sql"
networks:
  default:
    external:
      name: pronet
